name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prereqs
      run: sudo apt install libssl-dev libcurl4 libcurl4-openssl-dev libsodium-dev libzmq3-dev libczmq-dev libhiredis-dev

#   - name: configure
#     run: ./configure
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
